shop_info = {
  "Haci'nin Yeri - Yigit Lokantasi": {"Type": "Restaurant"},
  "Pizza Fellas": {"Type": "Pizzeria / Pizza shop"},
  "Cafe Inn": {"Type": "Cafe"},
  "Riviera": {"Type": "Restaurant "},
  "Sakip Usta Gaziantep": {"Type": "Restaurant (Gaziantep cuisine / kebab)"},
  "Imam Cagdas": {"Type": "Restaurant (famous Turkish lokanta)"},
  "Gold Semaver": {"Type": "Tea house / Cafe (traditional teas/beverages)"},
  "Fethiye Dondurmacisi": {"Type": "Ice cream shop / Gelato"},
  "My Friends Burger": {"Type": "Burger joint / Fast-casual"},
  "Mcdonalds Fethiye": {"Type": "Fast Food (McDonald's)"},
  "Pukka Marmaris": {"Type": "Restaurant / Cafe"},
  "Starbucks Bodrum": {"Type": "Cafe / Coffee shop"},
  "Churchill Bistro": {"Type": "Bistro / Restaurant"},
  "Leman Kultur": {"Type": "Cafe / Restaurant / Cultural bar"},
  "Tatbak": {"Type": "Restaurant (lahmacun / pide style)"},
  "Guzel Koy Cafe": {"Type": "Cafe"},
  "Cemo Etliekmek": {"Type": "Restaurant (etliekmek specialty)"},
  "Korelee": {"Type": "Restaurant (Korean)"},
  "Patso Burger": {"Type": "Burger joint / Fast food"},
  "Vefa Bozacisi": {"Type": "Traditional beverage shop (boza seller)"},
  "Salacak": {"Type": "Restaurant "},
  "Nusr-et": {"Type": "Steakhouse / High-end restaurant"},
  "Tuana Restaurant": {"Type": "Restaurant"},
  "Cici Tantuni": {"Type": "Tantuni shop / Fast-casual (wraps)"},
  "Bunbun Kas": {"Type": "Restaurant"},
  "Gulcimen Aspava": {"Type": "Aspava-style diner / Restaurant"},
  "Nazar Cafe": {"Type": "Cafe"},
  "Alsancak Firin": {"Type": "Bakery"},
  "Sushico": {"Type": "Sushi / Japanese restaurant"},
  "Sardalye": {"Type": "Seafood restaurant / Fish place"},
  "Kumrucu Omur": {"Type": "Kumru sandwich shop / Fast-casual"},
  "Kofteci Yusuf": {"Type": "Köfte restaurant / Grill"},
  "Bogazkoy Restaurant": {"Type": "Restaurant"},
  "Nesh": {"Type": "Restaurant"},
  "Flash": {"Type": "Restaurant / Cafe / Fast food"},
  "Metanet Lokantasi": {"Type": "Lokanta / Canteen-style restaurant"},
  "Midpoint": {"Type": "Casual dining restaurant & bar (chain)"},
  "Pecko Firin Atakum": {"Type": "Bakery / Patisserie"},
  "Bilice": {"Type": "Restaurant"},
  "Baruthane Pilavcisi": {"Type": "Pilav shop / Rice specialty vendor"},
  "Medeniyetler Sofrasi": {"Type": "Restaurant"},
  "Backyard": {"Type": "Restaurant"},
  "Alavara": {"Type": "Restaurant"},
  "Zula": {"Type": "Cafe / Bar / Restaurant"},
  "Kafros Pizzeria": {"Type": "Pizzeria"},
  "Kebabci Halil Usta": {"Type": "Kebab restaurant"},
  "Abidin Tantuni": {"Type": "Tantuni shop / Fast-casual"},
  "Ahsap Iskender": {"Type": "İskender kebab restaurant"},
  "Kasikla Restaurant": {"Type": "Restaurant"},
  "Askin Tostevi": {"Type": "Tost shop / Sandwich cafe (toasted sandwiches)"},
  "Pizzeria Remo": {"Type": "Pizzeria"},
  "Diyarbakir Ocakbasi Palace": {"Type": "Ocakbaşi / Grill restaurant (regional)"},
  "Kaliteci": {"Type": "Restaurant / Cafe"},
  "Sanukiya": {"Type": "Japanese noodle (udon) restaurant"},
  "KFC": {"Type": "Fast Food (KFC chicken)"},
  "Kruvasan": {"Type": "Bakery / Croissant shop"},
  "Midyeci Ahmet": {"Type": "Midye seller / Street seafood (stuffed mussels)"},
  "Kalkanoglu Pilav": {"Type": "Pilav shop / Rice specialty vendor"},
  "Monica Kitchen": {"Type": "Restaurant / Cafe"},
  "Sevinc Pastanesi": {"Type": "Patisserie / Bakery"},
  "Hasan Usta": {"Type": "Restaurant / Grill (common kebab name)"},
  "Magro": {"Type": "Restaurant / Cafe "},
  "Duveroglu": {"Type": "Restaurant (likely grill/kebab)"},
  "Rumeli Iskembecisi": {"Type": "Iskembeci / Tripe soup specialist (traditional meat soup)"},
  "Ege Vera": {"Type": "Restaurant (Aegean cuisine likely)"},
  "Antakya Mutfagi": {"Type": "Restaurant (Antakya / Hatay regional cuisine)"},
  "Mevlana Lokantasi": {"Type": "Lokanta / Restaurant"},
  "Balikci Tanju": {"Type": "Fish / Seafood restaurant"},
  "Yesemek": {"Type": "Restaurant / Cafe "},
  "Umut Pide": {"Type": "Pide shop / Bakery-style restaurant"},
  "Sema Gozleme": {"Type": "Gözleme stall / Turkish flatbread cafe"},
  "Asucan Restaurant": {"Type": "Restaurant"},
  "Ciya Sofrasi": {"Type": "Restaurant (famous Anatolian cuisine restaurant)"},
  "Koco Restaurant": {"Type": "Restaurant"},
  "Tavuk Dunyasi": {"Type": "Rotisserie / Chicken fast-casual chain"},
  "Kumsal Lokantasi": {"Type": "Lokanta / Restaurant (likely seaside)"},
  "Salih Usta": {"Type": "Restaurant / Grill "},
  "Red Dragon": {"Type": "Chinese restaurant"},
  "Mado": {"Type": "Dessert cafe / Patisserie / Ice-cream & Turkish desserts chain"},
  "Classic Thai": {"Type": "Thai restaurant"},
  "Inegol Restaurant": {"Type": "Restaurant (İnegöl köfte style likely)"},
  "Karakoy Lokantasi": {"Type": "Lokanta / Restaurant"},
  "Mersinli Cigerci Apo": {"Type": "Ciğerci / Liver specialist restaurant"},
  "Baskent Aspava": {"Type": "Aspava-style diner / Restaurant"},
  "Sini Mugla": {"Type": "Restaurant / Local eatery"},
  "Fikret Balik Restaurant": {"Type": "Fish / Seafood restaurant"},
  "Kocak Baklava": {"Type": "Baklava shop / Dessert shop"},
  "Kadineli": {"Type": "Patisserie / Cafe"},
  "Anzelha": {"Type": "Restaurant / Cafe"},
  "Akpinar Restaurant": {"Type": "Restaurant"},
  "Kebabci Mahmut": {"Type": "Kebab restaurant"},
  "J Burber": {"Type": "Burger joint"},
  "Popeyes": {"Type": "Fast Food (Popeyes chicken)"},
  "Say Cheese": {"Type": "Fast-casual / Sandwiches / Grilled cheese style cafe"},
  "Kukis Suadiye": {"Type": "Bakery / Cookie shop / Cafe"},
  "Lipa": {"Type": "Restaurant"},
  "Minoa": {"Type": "Restaurant (likely Greek / Mediterranean)"},
  "Suflor": {"Type": "Restaurant / Cafe"},
  "Berdan Doner": {"Type": "Döner / Doner kebab shop"},
  "Miss Pizza": {"Type": "Pizzeria"}
}